workflows:
  android-workflow:
    name: Android APK Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2
    scripts:
      - name: Set Android SDK location
        script: |
          cd android || echo "Pas de sous-dossier android, reste à la racine"
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
      - name: Regenerate Gradle Wrapper
        script: |
          cd android || echo "Pas de sous-dossier android"
          gradle wrapper
      - name: Fix gradlew permissions
        script: |
          cd android || echo "Pas de sous-dossier android"
          chmod +x gradlew
      - name: Build Android APK
        script: |
          cd android || echo "Pas de sous-dossier android"
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
      - app/build/outputs/apk/release/*.apk
