-- ============================================================
-- Z SCHOOL — Schéma Supabase
-- À exécuter dans : Dashboard > SQL Editor > New query > Run
-- ============================================================

create table if not exists public.formations (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  title text not null,
  author text not null default '',
  platform text not null default '',
  category text not null default '',
  description text not null default '',
  logo_path text,
  gradient_index int not null default 0,
  priority int not null default 1,
  start_date bigint,
  target_date bigint,
  created_at bigint not null default (extract(epoch from now()) * 1000)::bigint,
  archived boolean not null default false
);

create table if not exists public.modules (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  formation_id bigint not null references public.formations(id) on delete cascade,
  name text not null,
  duration_minutes int not null default 30,
  planned_date bigint,
  done boolean not null default false,
  position int not null default 0
);

create table if not exists public.skills (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  formation_id bigint not null references public.formations(id) on delete cascade,
  name text not null,
  level int not null default 0,
  icon text
);

create table if not exists public.resources (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  formation_id bigint not null references public.formations(id) on delete cascade,
  title text not null,
  url text not null default '',
  icon text
);

create table if not exists public.focus_sessions (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  module_id bigint not null references public.modules(id) on delete cascade,
  started_at bigint not null,
  duration_seconds int not null
);

-- Row Level Security : chaque utilisateur ne voit que SES lignes.
alter table public.formations enable row level security;
alter table public.modules enable row level security;
alter table public.skills enable row level security;
alter table public.resources enable row level security;
alter table public.focus_sessions enable row level security;

create policy "own formations" on public.formations for all
  using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "own modules" on public.modules for all
  using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "own skills" on public.skills for all
  using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "own resources" on public.resources for all
  using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "own focus_sessions" on public.focus_sessions for all
  using (auth.uid() = user_id) with check (auth.uid() = user_id);
